// Auto-generated by sync.py — do not edit
// Last sync: 2026-09-03T17:40:59
var TASKS = [
  {
    "section": "OTA Releases",
    "cat": "cat-ota",
    "tasks": [
      {
        "name": "Topaz OTA release for Wificonfig, wifi expansion, and possibly consumer keyguard",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-09-30"
      },
      {
        "name": "Obsidian 11 ET2.0 release",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-09-30"
      },
      {
        "name": "Sapphire 11 ET2.0 release",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-09-30"
      },
      {
        "name": "Amber 2GB - FT shipping image update",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-09-03"
      },
      {
        "name": "G700 Thermal hotfix",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-09-15"
      },
      {
        "name": "Amber 2GB Day 1 OTA - G700 single image",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-12-07"
      },
      {
        "name": "Pheonix firmware release",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-12-01"
      },
      {
        "name": "Test sync",
        "completed": false,
        "assignee": null,
        "due": "2026-09-04"
      }
    ]
  },
  {
    "section": "Factory Releases",
    "cat": "cat-factory",
    "tasks": [
      {
        "name": "Amber 2GB - shipping image release to factory",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-09-11"
      },
      {
        "name": "Amber 2GB Day 1 OTA - G700 single image",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-12-21"
      }
    ]
  },
  {
    "section": "In Progress",
    "cat": "cat-progress",
    "tasks": [
      {
        "name": "Raccoon ongoing refinement",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-09-30",
        "start": "2026-07-01"
      },
      {
        "name": "Amber 2GB - System optimization for 2GB RAM",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-09-30",
        "start": "2026-07-01"
      },
      {
        "name": "G700 Thermal Hotfix",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-09-14",
        "start": "2026-08-17"
      },
      {
        "name": "Topaz OTA update for Sept. 2026",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-09-04",
        "start": "2026-08-14"
      },
      {
        "name": "Obsidian OTA update for Sept. 2026",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-07-31",
        "start": "2026-07-01"
      },
      {
        "name": "Sapphire OTA update for Sept. 2026",
        "completed": false,
        "assignee": "Winston Lee",
        "due": "2026-09-11",
        "start": "2026-07-01"
      }
    ]
  },
  {
    "section": "Upcoming Priorities",
    "cat": "cat-upcoming",
    "tasks": [
      {
        "name": "Wificonfig - Network Monitor",
        "completed": false,
        "assignee": "Winston Lee"
      },
      {
        "name": "Amber 2GB Day 1 OTA - G700 single image",
        "completed": false,
        "assignee": "Winston Lee"
      },
      {
        "name": "Android 15 on Amber 2GB",
        "completed": false,
        "assignee": "Winston Lee"
      }
    ]
  },
  {
    "section": "Done",
    "cat": "cat-done",
    "tasks": [
      {
        "name": "Qbert 11 ET2.0 OTA release",
        "completed": true,
        "assignee": "Winston Lee",
        "due": "2026-07-01"
      },
      {
        "name": "Qbert OTA update for Sept. 2026",
        "completed": true,
        "assignee": "Winston Lee",
        "due": "2026-06-19",
        "start": "2026-05-04"
      },
      {
        "name": "Wificonfig - work on boot",
        "completed": true,
        "assignee": null,
        "due": "2026-07-29"
      },
      {
        "name": "Wificonfig - self-exit",
        "completed": true,
        "assignee": null,
        "due": "2026-08-14"
      }
    ]
  }
];
